// Generated by opengeodeweb-microservice-generate, do not edit.
import type json from "./pegghy_back_schemas.json";

export interface HealthcheckParams {
}

export interface ErrorResponse {
    code:        number;
    description: string;
    name:        string;
}

// `__params` and `__response` only exist at type level, to infer request/response types from a schema.
// A type alias (not an interface) keeps the implicit index signature of the JSON type it is intersected with.
export type TypedSchema<Params, Response> = {
  readonly __params?: Params;
  readonly __response?: Response;
};

export interface Schemas {
  readonly pegghy_back: {
    readonly healthcheck: (typeof json)["pegghy_back"]["healthcheck"] & TypedSchema<HealthcheckParams, unknown>;
  };
}

declare const schemas: Schemas;
export default schemas;
